name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    env:
      PUB_CACHE: /home/runner/.pub-cache
      FLUTTER_HOME: /opt/hostedtoolcache/flutter
      PATH: /opt/hostedtoolcache/flutter/bin:$PATH

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          architecture: x64

      - name: Force Flutter context
        run: flutter --version

      - name: Flutter doctor
        run: flutter doctor

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project
        run: flutter analyze

      - name: Run tests
        run: flutter test
